### ISSUE TITLE
TaperTrace, TaperCPW styles

### ISSUE THREAD

**Issue by ajkeller34** [PainterQubits/Devices.jl#24]
Given how often we want to taper a path it makes sense to make proper style types.

**Comment by platawiec** [comment]
Hi, just found this excellent package. I can implement these styles. Just want to check in on how you would like this done and check my understanding: should I add a /src/render/tapers.jl file and overload `render!`?

**Comment by ajkeller34** [comment]
Thanks for the feedback. That'd be great if you're up for it. You would also need to add a /src/paths/contstyles/tapers.jl file to define the styles. To be clear, these styles should just do a linear ramp of the trace width (trace and gap widths ramp independently in the case of TaperCPW). I think this should speed up rendering of tapers substantially.

You should be aware that we sometimes break this package when we have new ideas. It's not even a registered package. You're welcome to use it of course but you may want to record the git commit of Devices.jl when you have a script that is working, otherwise it your script may stop working if you update the package.

**Comment by ajkeller34** [comment]
Closed by the awesome PR #29
