### ISSUE TITLE
Taper issues

### ISSUE THREAD

**Issue by ajkeller34** [PainterQubits/Devices.jl#39]
From @eunjongkim 

> I noticed some cases of Paths.Taper() failing on my code and wanted to report this bug. [...] It seems that Paths.Taper() is not rendering properly for some reasons I couldn’t figure out.
>
> While trying to work with Paths.TaperCPW style, I noticed that constructors for Paths.TaperTrace and Paths.TaperCPW are incorrectly defined on paths\contstyles\tapers.jl
The functions in line 8 and line 24 of the file must have names `TaperTrace` and `TaperCPW` if I’m understanding the code correctly (currently, they are both overloading the method for `CPW`). This resolved the issue in my code but Paths.Taper() style is still not working.

There is a `handle_generic_tapers!` method that gets called from within [render!(::Cell, ::Path{T}, ::Meta) where {T}](https://github.com/PainterQubits/Devices.jl/blob/023f8e8d01d05b86283a0584311873bc15e164f7/src/render/paths.jl#L23) that doesn't detect nodes that have been `simplify!`-ied. I think @platawiec wrote most of the taper code so I haven't delved too much into the details. I don't have time to investigate / fix it right now. Regarding the constructors, I guess it does seem kind of misleading to overload `CPW` and `Trace` that way.

**Comment by platawiec** [comment]
Thanks for the note, I'll have a look at how `simplify!` is interacting with `handle_generic_tapers!`. A MWE of the bug would help greatly.
