### ISSUE TITLE
meander! function gives incorrect pathlength of the output when the input argument α is negative

### ISSUE THREAD

**Issue by eunjongkim** [PainterQubits/Devices.jl#40]
Hi,

I have noticed that `meander!` function gives incorrect result when the input argument `α` is negative. That is, one can use this function to generate meandering path only when it's starting from positive turn. For meander paths starting from negative turn, there is no error coming from the function but the pathlength of the output path differs a lot from the input argument `len`. 

I have checked that a simple correction resolves this issue:
on line 653 of `path.jl`:
```
unit = straightlen + r * abs(α)
```

Best,
Eunjong

**Comment by ajkeller34** [comment]
Closed by #36
