### ISSUE TITLE
Errors on 0.7

### ISSUE THREAD

**Issue by platawiec** [PainterQubits/Devices.jl#44]
The master branch is failing on Julia 0.7. I see the `julia07` branch works ok, with some deprecations, but haven't tested too deeply. What's the status of the migration to 0.7, and is there any way we could help?

**Comment by ajkeller34** [comment]
I am working on it here and there, hopefully ready sometime next week. Out of curiosity, may I ask how many people are using this in your group? Despite this being a public repository I hadn't really considered that others might actually use it :)

**Comment by platawiec** [comment]
I think I was the only one in my group who used it, though I did recommend it to others. I've since graduated, and the start-up I work for does use it exclusively ;)
